version: '3.8'
services:
  example-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=node_example
      - MYSQL_ROOT_PASSWORD=mysql-pw
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
  node-app:
    build: .
    depends_on:
      - example-mysql
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge