apiVersion: v1
kind: Service
metadata:
  name: example-docker-service-service
spec:
  type: NodePort
  selector:
    app: example-docker-service
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007